name:                pending-requests
version:             0.1.0.0
license:             BSD3

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- lens

library:
  source-dirs: src

tests:
  pending-requests-test:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-expectations
    - pending-requests
