name:                aer-quorum
version:             0.1.0.0
license:             BSD3

dependencies:
- base >= 4.7 && < 5
- containers
- lens

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  aer-quorum-test:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aer-quorum
    - hspec
    - hspec-expectations
